language: node_js
node_js:
  - "10"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9

before_install:
  - npm explore npm -g -- npm install node-gyp@latest

branches:
  only:
  - master

script:
  - npm test
  - npm run demo:build
# deploy:
#   provider: pages
#   skip-cleanup: true
#   local-dir: demo
#   on:
#     branch: master
