name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

jobs:
  test:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
